### ISSUE TITLE
[Feature] Support i2p

### ISSUE THREAD

**Issue by jnjhbdjhkn** [paperwork/web#1]
**Feature**: Make accessible via i2p.
**Why?**: Mainly for privacy and security, but also to promote decentralized communication.
**Related Links/How To**:
https://www.invidio.us/watch?v=2ylW85vc7SA

https://geti2p.net/en/about/media

https://geti2p.net/

https://www.wikipedia.org/wiki/I2p

**Comment by mrusme** [comment]
@jnjhbdjhkn thanks for this suggestion. However, I don't see in which way the Paperwork project or the web UI in specific could actually **support** this incentive. Feel free to correct me, if I got your suggestion wrong, though. From my point of view, I2P is (similar to TOR) an overlay network. So basically, if you set up a I2P web server to run the web UI and proxy to the API everything should work out of the box.

However, keep in mind that this scenario is in fact contradictory to what Paperwork tries to empower the people to do. The idea behind Paperwork is to have it running **inside** your network and thereby own the service and the data. I don't see a real reason anyone would want to set up a publicly accessible instance and make it available through I2P or Tor. If you have Paperwork running inside a closed network, you're able to "dial-in" by using an OpenVPN server that helps you gain secure access to the network from everywhere.

On a side note, the long term goal of the Paperwork project is to provide the ability to inter-connect instances with each other, meaning that (in theory) every user could run a Paperwork instance locally on her/his computer while using a decentralised feature (*yet to be built*) to hook up with other instances on the internet. Paperwork will in fact incentivise people to **not** host it the way such services are usually being hosted these days.

If there should be any misconception on my side regarding your i2p suggestion, feel free to follow up! :-)
